### ISSUE TITLE
Metrics not work after update to roxy-wi

### ISSUE THREAD

**Issue by ThibautBascoulergue** [hap-wi/roxy-wi#288]
Hello,

After update to Roxy-wi, my metric doens't work.

When i start the pyton scrypt manually i go an error 👍 
![image](https://user-images.githubusercontent.com/42678960/130246671-40584025-8ce8-4a71-8822-18f55f224e19.png)

Thx

**Comment by ThibautBascoulergue** [comment]
Version installed 👍 
![image](https://user-images.githubusercontent.com/42678960/130246843-e8c1cb09-e656-4f37-9393-a186eff4040d.png)

**Comment by Aidaho12** [comment]
Hello,

strange error, because if there isn't sql, nothing would work

Could you show the first 10 lines from worker and ls -la /var/www/haproxy-wi/app/sql.py ?

**Comment by ThibautBascoulergue** [comment]
10 lines of metric_worker.py

#!/usr/bin/env python3.6
import subprocess
from subprocess import check_output, CalledProcessError
import time
import argparse
import os
import sys
sys.path.append(os.path.join(sys.path[0], os.path.dirname(os.getcwd())))
sys.path.append(os.path.join(sys.path[0], os.getcwd()))
import sql
import funct
import signal


And result of : 
[root@SRVHAPROXY-WI ~]# ls -la /var/www/haproxy-wi/app/sql.py
-rwxr-xr-x. 1 apache apache 83483 15 août  08:31 /var/www/haproxy-wi/app/sql.py

**Comment by Aidaho12** [comment]
hm... I don't even know

**Comment by ThibautBascoulergue** [comment]
What is annoying is that I have no graph: /

![image](https://user-images.githubusercontent.com/42678960/130639222-30572487-a9fa-4a2c-aed4-154b6bd0458c.png)

**Comment by Aidaho12** [comment]
Of course, service does not work вторник, 24 августа 2021г., 17:53 +03:00 от ThibautBascoulergue  ***@***.*** :

**Comment by ThibautBascoulergue** [comment]
Strange because service seems to be launched

![image](https://user-images.githubusercontent.com/42678960/130643210-aac98281-b5f5-470a-aef2-0caa1284a522.png)

**Comment by Aidaho12** [comment]
I think it restarts always. Have you checked the metrics log?

**Comment by ThibautBascoulergue** [comment]
[root@SRVHAPROXY-WI log]# cat metrics-20210824.log
Aug 24 15:11:35 Metrics master started
Aug 24 15:11:35 Master started new metrics worker for: 10.1.2.248
Aug 24 15:11:35 Master started new metrics worker for: 10.1.1.23
Aug 24 15:11:35 Master started new metrics worker for: 10.1.2.246
Aug 24 15:11:35 Master started new metrics worker for: 10.1.2.23
Aug 24 15:11:35 Master started new metrics worker for: 10.1.2.247
Aug 24 15:11:35 Master started new metrics worker for: 10.1.2.24
Aug 24 15:11:35 Master started new metrics worker for: 10.1.4.143
Aug 24 15:11:36 Master started new metrics worker for: 10.1.1.7
Aug 24 15:11:36 Master started new metrics worker for: 10.1.4.144
Aug 24 15:11:36 Master started new metrics worker for: 10.1.2.249

**Comment by ThibautBascoulergue** [comment]
And checker log 
Aug 24 15:21:24 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 2157, max_conn is: 1500
Aug 24 15:21:44 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:22:44 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 2132, max_conn is: 1500
Aug 24 15:23:04 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:24:04 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 2088, max_conn is: 1500
Aug 24 15:24:24 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:25:25 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 2067, max_conn is: 1500
Aug 24 15:25:44 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:26:45 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 1988, max_conn is: 1500
Aug 24 15:27:05 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:28:05 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 2014, max_conn is: 1500
Aug 24 15:28:25 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:29:25 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 1976, max_conn is: 1500
Aug 24 15:29:45 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:30:45 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 1891, max_conn is: 1500
Aug 24 15:31:05 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:32:05 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 1922, max_conn is: 1500
Aug 24 15:32:25 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:33:25 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 1930, max_conn is: 1500
Aug 24 15:33:45 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:34:46 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 1906, max_conn is: 1500
Aug 24 15:35:06 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:36:06 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 1903, max_conn is: 1500
Aug 24 15:36:26 Master has started a new HAProxy worker for: 10.1.2.24
Aug 24 15:37:26 There are too many connections on: 10.1.2.24 backend portal-backend_ipvANY, connections are 1860, max_conn is: 1500
Aug 24 15:37:46 Master has started a new HAProxy worker for: 10.1.2.24

**Comment by Aidaho12** [comment]
Yeap, services is always restarting. There is error log, look at it too. вторник, 24 августа 2021г., 18:38 +03:00 от ThibautBascoulergue  ***@***.*** :

***@***.*** log]# cat metrics-20210824.log

**Comment by ThibautBascoulergue** [comment]
[root@SRVHAPROXY-WI httpd]# tail -f roxy-wi.error.log
[Tue Aug 24 17:06:00.716314 2021] [cgi:error] [pid 83131:tid 83131] [client 10.109.2.6:51091] AH01215:     funct.logging('the server ' + name, ' has been updated ', haproxywi=1, login=1): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/users.py
[Tue Aug 24 17:06:00.716334 2021] [cgi:error] [pid 83131:tid 83131] [client 10.109.2.6:51091] AH01215:   File "/var/www/haproxy-wi/app/funct.py", line 140, in logging: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/users.py
[Tue Aug 24 17:06:00.716354 2021] [cgi:error] [pid 83131:tid 83131] [client 10.109.2.6:51091] AH01215:     log = open(log_path + "/roxy-wi-"+get_data('logs')+".log", "a"): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/users.py
[Tue Aug 24 17:06:00.716382 2021] [cgi:error] [pid 83131:tid 83131] [client 10.109.2.6:51091] AH01215: PermissionError: [Errno 13] Permission denied: '/var/www/haproxy-wi/log//roxy-wi-20210824.log': /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/users.py
[Tue Aug 24 17:06:02.425653 2021] [cgi:error] [pid 83131:tid 83131] [client 10.109.2.6:51091] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/users.py
[Tue Aug 24 17:06:02.425693 2021] [cgi:error] [pid 83131:tid 83131] [client 10.109.2.6:51091] AH01215:   File "/var/www/haproxy-wi/app/options.py", line 1895, in <module>: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/users.py
[Tue Aug 24 17:06:02.425719 2021] [cgi:error] [pid 83131:tid 83131] [client 10.109.2.6:51091] AH01215:     funct.logging('the server ' + name, ' has been updated ', haproxywi=1, login=1): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/users.py
[Tue Aug 24 17:06:02.425738 2021] [cgi:error] [pid 83131:tid 83131] [client 10.109.2.6:51091] AH01215:   File "/var/www/haproxy-wi/app/funct.py", line 140, in logging: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/users.py
[Tue Aug 24 17:06:02.425771 2021] [cgi:error] [pid 83131:tid 83131] [client 10.109.2.6:51091] AH01215:     log = open(log_path + "/roxy-wi-"+get_data('logs')+".log", "a"): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/users.py
[Tue Aug 24 17:06:02.425799 2021] [cgi:error] [pid 83131:tid 83131] [client 10.109.2.6:51091] AH01215: PermissionError: [Errno 13] Permission denied: '/var/www/haproxy-wi/log//roxy-wi-20210824.log': /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/users.py

**Comment by Aidaho12** [comment]
Do next:
chown apache:apache /var/www -R вторник, 24 августа 2021г., 18:47 +03:00 от ThibautBascoulergue  ***@***.*** :

***@***.*** httpd]# tail -f roxy-wi.error.log
