### ISSUE TITLE
create database issue

### ISSUE THREAD

**Issue by pakozack** [hap-wi/roxy-wi#300]
Hello,
I have an error when try to execute script create_db.py.
The stacktrace is

Traceback (most recent call last):
  File "./create_db.py", line 3, in <module>
    from sql import out_error
  File "/Storage/fs/www/haproxy-wi/app/sql.py", line 4, in <module>
    from db_model import *
  File "/Storage/fs/www/haproxy-wi/app/db_model.py", line 24, in <module>
    class User(BaseModel):
  File "/Storage/fs/www/haproxy-wi/app/db_model.py", line 25, in User
    user_id = AutoField(column_name='id')
NameError: name 'AutoField' is not defined

Any suggestion?

**Comment by Aidaho12** [comment]
Hello,
Probably you have installed an old peewee
