### ISSUE TITLE
HAProxy Config - No display

### ISSUE THREAD

**Issue by jeremypascaud** [hap-wi/roxy-wi#339]
Hello,

I installed ROXY "manually" on Centos 7.9 but I have a problem to display the configuration of the haproxy.cfg file:

Here are the logs :

[Fri Oct 07 15:39:58.776447 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215: /usr/local/lib64/python3.6/site-packages/peewee.py:4127: UserWarning: Unable to determine MySQL version: "5.5.68-mariadb", referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:39:58.776532 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:   warnings.warn('Unable to determine MySQL version: "%s"' % version), referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.530174 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215: /usr/local/lib64/python3.6/site-packages/peewee.py:4127: UserWarning: Unable to determine MySQL version: "5.5.68-mariadb", referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.530270 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:   warnings.warn('Unable to determine MySQL version: "%s"' % version), referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.531863 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215: Traceback (most recent call last):, referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.531941 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:   File "/var/www/haproxy-wi/app/options.py", line 1334, in <module>, referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.531970 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:     is_restart=is_restart), referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532050 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render, referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532089 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:     self.environment.handle_exception(), referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532176 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception, referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532227 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:     reraise(*rewrite_traceback_stack(source=source)), referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532306 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise, referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532339 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:     raise value.with_traceback(tb), referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532405 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:   File "templates/ajax/config_show.html", line 23, in top-level template code, referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532432 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:     {% for line in conf -%}, referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532503 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/runtime.py", line 545, in __next__, referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532531 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:     rv = next(self._iterator), referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532590 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:   File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode, referer: https://X.X.X.X/app/config.py?service=haproxy
[Fri Oct 07 15:40:00.532638 2022] [cgi:error] [pid 24175] [client X.X.X.X:50019] AH01215:     return codecs.ascii_decode(input, self.errors)[0], referer: https://X.X.X.X/app/config.py?service=haproxy

**Comment by Aidaho12** [comment]
Hi,

Looks like there are not asci characters in your config file

**Comment by jeremypascaud** [comment]
RESOLVED
Thank You
There was indeed a non-asci character
To find : grep --color='auto' -P -n "[\x80-\xFF]" /etc/haproxy/haproxy.cfg
