### ISSUE TITLE
Installed Roxy-wi does not work when accessing web console.

### ISSUE THREAD

**Issue by general2000vn** [hap-wi/roxy-wi#373]
The roxy-wi.error.log showed:
```
[Tue Jan 30 09:29:50.916780 2024] [:error] [pid 10317] [remote 172.16.5.227:16]     from flask import Flask

[Tue Jan 30 09:29:50.916822 2024] [:error] [pid 10317] [remote 172.16.5.227:16] ImportError: No module named flask

[Tue Jan 30 09:29:51.374719 2024] [:error] [pid 10317] [remote 172.16.5.227:28] mod_wsgi (pid=10317): Target WSGI script '/var/www/haproxy-wi/app/app.wsgi' cannot be loaded as Python module.

[Tue Jan 30 09:29:51.374838 2024] [:error] [pid 10317] [remote 172.16.5.227:28] mod_wsgi (pid=10317): Exception occurred processing WSGI script '/var/www/haproxy-wi/app/app.wsgi'.

[Tue Jan 30 09:29:51.374912 2024] [:error] [pid 10317] [remote 172.16.5.227:28] Traceback (most recent call last):

[Tue Jan 30 09:29:51.374987 2024] [:error] [pid 10317] [remote 172.16.5.227:28]   File "/var/www/haproxy-wi/app/app.wsgi", line 4, in <module>

[Tue Jan 30 09:29:51.375061 2024] [:error] [pid 10317] [remote 172.16.5.227:28]     from app import app as application

[Tue Jan 30 09:29:51.375088 2024] [:error] [pid 10317] [remote 172.16.5.227:28]   File "/var/www/haproxy-wi/app/__init__.py", line 1, in <module>

[Tue Jan 30 09:29:51.375132 2024] [:error] [pid 10317] [remote 172.16.5.227:28]     from flask import Flask

[Tue Jan 30 09:29:51.375172 2024] [:error] [pid 10317] [remote 172.16.5.227:28] ImportError: No module named flask

```

web page showed:

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

I tried to installed flask with `pip3 install flask` and it said the requirement already satisfied.

Please help

**Comment by Aidaho12** [comment]
Please, install all needed modules
